### PR TITLE
Exclude lein-protobuf + minor changes

### PR DESCRIPTION
**Pull request by arr-ee**
`clojure-protobuf` depends on `lein-protobuf`, which does two things:
- Adds a nifty `lein protobuf` command that compiles your `.proto` files
- Hijacks `lein javac`, forcing it to use some fucked up custom build of `protobuf-java`

By adding `lib` to resources we put "proper" protobuf library into the very beginning of classpath, fixing all the compilation errors that occur because `2.x` releases of protobuf-java are not backward/forward compatible.

So I decided to drop `lein-protobuf` dependency, which removes all the hooks and allows lein to use whatever we tell it in `dependencies`.
This also means we have to compile protos manually, so we might want to add a shortcut or whatever to `project.clj`, otherwise we might get more conflicts when system’s protobuf-java version does not match one from dependencies.

I also added some namespace-related stuff to the proto file, because all hail structure.

### CODE REVIEW

**Comment by arr-ee** [comment]
BTW I used `protoc --java_out=src/java/ resources/proto/realtime-bidding.proto --proto_path=resources/proto` to compile the proto file, then `lein run -m proto.core` to make sure everything works.

**Comment by dmitryn** [comment]
Thanks. I've updated protoc to 2.6.1 and pulled your changes, but still got compilation errors when i run `lein javac`

Here is my output: https://gist.github.com/trybeee/9377129e68f9ec1b5b84

**Comment by arr-ee** [comment]
That looks like protobuf-java version mismatch (which was caused by `lein-protobuf` before). Could you provide `lein classpath` output from your machine?

**Comment by dmitryn** [comment]
/Users/trybeee/Code/vagrant-virool/proto/test:/Users/trybeee/Code/vagrant-virool/proto/src:/Users/trybeee/Code/vagrant-virool/proto/dev-resources:/Users/trybeee/Code/vagrant-virool/proto/resources:/Users/trybeee/Code/vagrant-virool/proto/target/classes:/Users/trybeee/.m2/repository/clojure-complete/clojure-complete/0.2.3/clojure-complete-0.2.3.jar:/Users/trybeee/.m2/repository/org/clojure/tools.nrepl/0.2.6/tools.nrepl-0.2.6.jar:/Users/trybeee/.m2/repository/ordered-collections/ordered-collections/0.4.0/ordered-collections-0.4.0.jar:/Users/trybeee/.m2/repository/org/flatland/schematic/0.1.0/schematic-0.1.0.jar:/Users/trybeee/.m2/repository/org/clojure/tools.macro/0.1.1/tools.macro-0.1.1.jar:/Users/trybeee/.m2/repository/org/flatland/useful/0.9.0/useful-0.9.0.jar:/Users/trybeee/.m2/repository/org/flatland/protobuf/0.7.1/protobuf-0.7.1.jar:/Users/trybeee/.m2/repository/com/google/protobuf/protobuf-java/2.6.1/protobuf-java-2.6.1.jar:/Users/trybeee/.m2/repository/org/clojure/clojure/1.6.0/clojure-1.6.0.jar

**Comment by dmitryn** [comment]
Fixed here https://github.com/arr-ee/clojure-protobuf

**Comment by dmitryn** [comment]
To fix the issue remove these dependecies

```
[com.google.protobuf/protobuf-java "2.5.0"] 
[org.flatland/protobuf "0.7.1"]
```

and add new one  `[arre/protobuf "0.8.2"]`

**Pull request merged**
